# Generated by Django 2.1.5 on 2019-01-28 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_people_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='about',
            field=models.TextField(blank=True, help_text='Tell us about you!', max_length=300),
        ),
    ]
